# This file was generated by GoReleaser. DO NOT EDIT.
cask "chiffremento" do
  version "2.1.1"

  on_macos do
    on_arm do
      sha256 "d4fdbcfe5d5958bbdfd458598e6d13b8c01964b70ef50a97a747d5d9d8adbff9"
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v#{version}/chiffremento_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cf618339f3763cf29b67c45d3a5a2d22b435bdb4a8457aaa79664abb8ea7b0b7"
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v#{version}/chiffremento_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "350ee00ac164e17f04500bbb7afd63917a1aba400b20ef414e55d0f1b106b182"
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v#{version}/chiffremento_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f6e9f9badd3bc7ac03b12369287224206bf35be8a29eb3a934735f8f8dec1624"
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v#{version}/chiffremento_#{version}_linux_amd64.tar.gz"
    end
  end

  name "chiffremento"
  desc "Outil de chiffrement de fichiers en ligne de commande"
  homepage "https://github.com/ValMtp3/chiffremento-go-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chiffremento"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chiffremento"]
    end
  end

  # No zap stanza required
end
