# This file was generated by GoReleaser. DO NOT EDIT.
cask "chiffremento" do
  version "2.2.0"

  on_macos do
    on_arm do
      sha256 "89f675f0322338838e6540d54952ee6c1cb33bba3ccc76216d67e597fbdb6ea0"
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v#{version}/chiffremento_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b931b499e1e28a9c0d463a387667b1bd32868477d1891c37b7fedfa18a022d8f"
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v#{version}/chiffremento_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ddbc27c63bac2d3ece518897d54b5f2363456fac38d8b712c0a88c88be6e8732"
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v#{version}/chiffremento_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b7292e0d4c736f00ea4cbd0b351995264b2168622b27a978e43c33c46dd159ee"
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v#{version}/chiffremento_#{version}_linux_amd64.tar.gz"
    end
  end

  name "chiffremento"
  desc "Outil de chiffrement de fichiers en ligne de commande"
  homepage "https://github.com/ValMtp3/chiffremento-go-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chiffremento"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chiffremento"]
    end
  end

  # No zap stanza required
end
