# This file was generated by GoReleaser. DO NOT EDIT.
cask "chiffremento" do
  version "2.1.1"

  on_macos do
    on_arm do
      sha256 "ce17dad48ca87dc5835527b3af14a32037c65c3eb903ba49481c5646aa22ebe7"
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v#{version}/chiffremento_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "53d064d48e11b6f6dbe574daf4c474de2e6f36fb75181dcb94a0ac72b2ca5658"
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v#{version}/chiffremento_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8ce00e0a8ec05607c6684fe7e66abdbfe6371c6a5c52c37fc2cdfc6c0dcb6812"
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v#{version}/chiffremento_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0f522f4be3f21c16b3dbef58afc4361b3eec5d0dd175cef0c859f5db7f1cfa0d"
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v#{version}/chiffremento_#{version}_linux_amd64.tar.gz"
    end
  end

  name "chiffremento"
  desc "Outil de chiffrement de fichiers en ligne de commande"
  homepage "https://github.com/ValMtp3/chiffremento-go-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chiffremento"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chiffremento"]
    end
  end

  # No zap stanza required
end
