# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chiffremento < Formula
  desc "Outil de chiffrement CLI sécurisé et robuste en Go"
  homepage "https://github.com/valentinfiess/chiffremento-go-cli"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v1.1.0/chiffremento_1.1.0_darwin_amd64.tar.gz"
      sha256 "c57860e2f98a02a8b7c8b26757429d25afd5c7463e72c6943fb4775e1058d4cb"

      def install
        bin.install "chiffremento"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v1.1.0/chiffremento_1.1.0_darwin_arm64.tar.gz"
      sha256 "78914b260671719591b16b41ac5541071c7beb5a9b3f1068daaf8b945d07384e"

      def install
        bin.install "chiffremento"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v1.1.0/chiffremento_1.1.0_linux_amd64.tar.gz"
      sha256 "42f23929d992b86a3e97f16630f83e8aef46eb8c4ff23de932a527c065133ffd"
      def install
        bin.install "chiffremento"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v1.1.0/chiffremento_1.1.0_linux_arm64.tar.gz"
      sha256 "3e7c3f9ff14baeead922f856de82761fcf3e1659cf6658613e12905c6b4d979d"
      def install
        bin.install "chiffremento"
      end
    end
  end

  test do
    system "#{bin}/chiffremento -version"
  end
end
