# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chiffremento < Formula
  desc "Outil de chiffrement CLI sécurisé et robuste en Go"
  homepage "https://github.com/valentinfiess/chiffremento-go-cli"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v1.1.0/chiffremento_1.1.0_darwin_amd64.tar.gz"
      sha256 "53cbf795e994927081a4b5676761158dc69eff0abebe5cf9df5d9c5bd3ade023"

      def install
        bin.install "chiffremento"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v1.1.0/chiffremento_1.1.0_darwin_arm64.tar.gz"
      sha256 "567dd4b26240697a08110849aca1de85474d13b204a6d397a5787235cbaed4c5"

      def install
        bin.install "chiffremento"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v1.1.0/chiffremento_1.1.0_linux_amd64.tar.gz"
      sha256 "b3f2ccb53aaa2bb7e17b04f4e5fbf0ebbd6fbed004fb402927ce76ed8e11a06f"
      def install
        bin.install "chiffremento"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ValMtp3/chiffremento-go-cli/releases/download/v1.1.0/chiffremento_1.1.0_linux_arm64.tar.gz"
      sha256 "21901af2239e93b5bdf89aa899112e86a54506c1dc2451ef80a55ac3eb3e0861"
      def install
        bin.install "chiffremento"
      end
    end
  end

  test do
    system "#{bin}/chiffremento -version"
  end
end
